### PR TITLE
[APPS-2863] new translations

### PR DESCRIPTION
**Pull request by pmgrove**
:v:

/cc @zendesk/vegemite, @injuhwang, @ydrain, @mariasica 

### Description

Updated translations

### References
* JIRA: https://zendesk.atlassian.net/browse/APPS-2863

### Risks
none

### CODE REVIEW

**Comment by sandlerr** [comment]
:+1:

**Comment by mariasica** [comment]
Thanks Phil, very much appreciated! We did not test this apps yet (we did only a few of them for now) but will start after they are all up-to date (so more edits may come after LQA, but we will not bother you while you are in Dublin, promise!). THANKS!!!! :+1:

**Comment by pmgrove** [comment]
@injuhwang, unfortunately it is @acottrell that will be in Dublin not me... I will still be here in Melbourne! :)

**Comment by mariasica** [comment]
oh I misunderstood then!!!

**Comment by injuhwang** [comment]
Good news (for us...), @pmgrove!! 😅

**Comment by pmgrove** [comment]
haha, no worries @mariasica, I also tagged the wrong person above as well... obviously need more :coffee:

**Comment by ocke** [comment]
good job phil :+1:

**Pull request merged**
