### PR TITLE
updated translations

### PR DESCRIPTION
**Pull request by pmgrove**
:v:

Updated translations

/cc @zendesk/vegemite @ydrain @injuhwang 

### References
 - Jira link: https://zendesk.atlassian.net/browse/OFFAPPS-667

### Risks
 - None

### CODE REVIEW

**Comment by sandlerr** [comment]
:+1:

**Comment by sandlerr** [comment]
isn't this a @zendesk/platypus project?

**Comment by pmgrove** [comment]
cc: @liulikun

**Comment by liulikun** [comment]
This seems JIRA on premise integration. :+1:

**Comment by ydrain** [comment]
:+1: 

@pmgrove I need to figure out localization of the JIRA on premise integration too. :sweat_smile: Are you the person I should talk to?

**Comment by pmgrove** [comment]
@ydrain, we are hiring a new PM for the JIRA Server integration but I am the interim PM so lets catch up this week.

**Pull request merged**
